name: Page analyzer

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: snok/install-uv@v3
        with:
          cache: 'true'
      - name: Install dependencies
        run: 
          make install
      - name: Run linter and pytest
        run :
          make lint